---
#========================================
#   Global Settings
#========================================
global_settings:
  intersight_fqdn: cg-ia-test-1.lab16.mel.ciscolabs.com # rebuilt new CVA
  tags:
    - key: "Module"
      value: "easy-imm"
    - key: "Version"
      value: "4.2.11-20250122215055407"
