---
#===========================================
#   Policies -> Environment - Variables
#===========================================
ABC:
  policies:
    power:
      - description: 5108 Power Policy
        name: 'PP_5108'
        power_redundancy: Grid
      - description: 9508 Power Policy
        name: 'PP_9508'
        power_allocation: 5600
        power_redundancy: Grid
      - description: server Power Policy
        name: 'PP_server'
        power_redundancy: Grid
        power_restore: LastState
    thermal:
      - description: 5108 Thermal Policy
        fan_control_mode: Balanced
        name: 'TP_5108'
      - description: 9508 Thermal Policy
        fan_control_mode: Balanced
        name: 'TP_9508'
      - description: server Thermal Policy
        fan_control_mode: Balanced
        name: 'TP_server'
